default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  url: 'postgres://rjksziqzsxijlj:dda679d1e8e895d3b355f3d45655b8fbfe1cf99bd76668b36d6eb3df9df2f0ac@ec2-52-209-134-160.eu-west-1.compute.amazonaws.com:5432/d7ccl3h2r79qio'
  user: rjksziqzsxijlj
  database: d7ccl3h2r79qio

test:
  <<: *default
  database: paradigma_test

production:
  <<: *default
  url: 'postgres://rjksziqzsxijlj:dda679d1e8e895d3b355f3d45655b8fbfe1cf99bd76668b36d6eb3df9df2f0ac@ec2-52-209-134-160.eu-west-1.compute.amazonaws.com:5432/d7ccl3h2r79qio'
  user: rjksziqzsxijlj
  database: d7ccl3h2r79qio
